"""HCPCS/CPT code descriptions for the ~450 most common Medicaid billing codes.

Source: CMS HCPCS Level II and CPT code sets (public domain).
Unknown codes are left unmapped — callers should treat missing keys as blank,
not attempt to guess a description.
"""

HCPCS_DESCRIPTIONS: dict[str, str] = {
    # ---------------------------------------------------------------------------
    # E&M — Office / Outpatient Visits
    # ---------------------------------------------------------------------------
    "99201": "Office visit, new patient, minimal (deprecated 2021)",
    "99202": "Office visit, new patient, straightforward",
    "99203": "Office visit, new patient, low complexity",
    "99204": "Office visit, new patient, moderate complexity",
    "99205": "Office visit, new patient, high complexity",
    "99211": "Office visit, established patient, minimal",
    "99212": "Office visit, established patient, straightforward",
    "99213": "Office visit, established patient, low complexity",
    "99214": "Office visit, established patient, moderate complexity",
    "99215": "Office visit, established patient, high complexity",
    # E&M — Preventive Medicine
    "99381": "Preventive visit, new patient, infant (<1 yr)",
    "99382": "Preventive visit, new patient, age 1-4",
    "99383": "Preventive visit, new patient, age 5-11",
    "99384": "Preventive visit, new patient, age 12-17",
    "99385": "Preventive visit, new patient, age 18-39",
    "99386": "Preventive visit, new patient, age 40-64",
    "99387": "Preventive visit, new patient, age 65+",
    "99391": "Preventive visit, established, infant (<1 yr)",
    "99392": "Preventive visit, established, age 1-4",
    "99393": "Preventive visit, established, age 5-11",
    "99394": "Preventive visit, established, age 12-17",
    "99395": "Preventive visit, established, age 18-39",
    "99396": "Preventive visit, established, age 40-64",
    "99397": "Preventive visit, established, age 65+",
    # E&M — Hospital
    "99221": "Initial hospital care, straightforward/low complexity",
    "99222": "Initial hospital care, moderate complexity",
    "99223": "Initial hospital care, high complexity",
    "99231": "Subsequent hospital care, straightforward/low complexity",
    "99232": "Subsequent hospital care, moderate complexity",
    "99233": "Subsequent hospital care, high complexity",
    "99234": "Observation/inpatient hospital care, straightforward",
    "99235": "Observation/inpatient hospital care, moderate complexity",
    "99236": "Observation/inpatient hospital care, high complexity",
    "99238": "Hospital discharge day management, ≤30 min",
    "99239": "Hospital discharge day management, >30 min",
    # E&M — Emergency Department
    "99281": "ED visit, self-limited or minor",
    "99282": "ED visit, low complexity",
    "99283": "ED visit, moderate complexity",
    "99284": "ED visit, moderately high complexity",
    "99285": "ED visit, high complexity",
    # E&M — Nursing Facility
    "99304": "Initial nursing facility care, straightforward/low",
    "99305": "Initial nursing facility care, moderate complexity",
    "99306": "Initial nursing facility care, high complexity",
    "99307": "Subsequent nursing facility care, straightforward",
    "99308": "Subsequent nursing facility care, low complexity",
    "99309": "Subsequent nursing facility care, moderate complexity",
    "99310": "Subsequent nursing facility care, high complexity",
    "99315": "Nursing facility discharge, ≤30 min",
    "99316": "Nursing facility discharge, >30 min",
    # E&M — Home Health
    "99341": "Home visit, new patient, straightforward",
    "99342": "Home visit, new patient, low complexity",
    "99343": "Home visit, new patient, moderate complexity",
    "99344": "Home visit, new patient, moderately high complexity",
    "99345": "Home visit, new patient, high complexity",
    "99347": "Home visit, established, straightforward",
    "99348": "Home visit, established, low complexity",
    "99349": "Home visit, established, moderate complexity",
    "99350": "Home visit, established, moderately high complexity",
    # E&M — Critical Care
    "99291": "Critical care, first 30-74 min",
    "99292": "Critical care, each additional 30 min",
    # E&M — Prolonged Services
    "99354": "Prolonged office service, first hour",
    "99355": "Prolonged office service, each additional 30 min",
    # E&M — Telehealth / After-Hours
    "99050": "After-hours service (in addition to basic service)",
    "99051": "After-hours service, evening/weekend/holiday",
    "99053": "Service 10 pm–8 am or holiday",
    "99056": "Service normally in office, provided out of office",
    "99058": "Office services on emergency basis",
    "99441": "Phone call, physician, 5-10 min",
    "99442": "Phone call, physician, 11-20 min",
    "99443": "Phone call, physician, 21-30 min",
    # E&M — Tobacco / Alcohol / Obesity Counseling
    "99406": "Smoking/tobacco cessation counseling, 3-10 min",
    "99407": "Smoking/tobacco cessation counseling, >10 min",
    "99408": "Alcohol/substance abuse assessment, 15-30 min",
    "99409": "Alcohol/substance abuse assessment, >30 min",
    # E&M — Transitional Care
    "99495": "Transitional care management, moderate complexity, 14 days",
    "99496": "Transitional care management, high complexity, 7 days",
    # ---------------------------------------------------------------------------
    # Mental Health / Psychotherapy
    # ---------------------------------------------------------------------------
    "90791": "Psychiatric diagnostic evaluation",
    "90792": "Psychiatric diagnostic evaluation with medical services",
    "90832": "Psychotherapy, 30 min",
    "90833": "Psychotherapy add-on, 30 min (with E&M)",
    "90834": "Psychotherapy, 45 min",
    "90836": "Psychotherapy add-on, 45 min (with E&M)",
    "90837": "Psychotherapy, 60 min",
    "90838": "Psychotherapy add-on, 60 min (with E&M)",
    "90839": "Psychotherapy for crisis, first 60 min",
    "90840": "Psychotherapy for crisis, each additional 30 min",
    "90845": "Psychoanalysis",
    "90846": "Family psychotherapy without patient",
    "90847": "Family psychotherapy with patient",
    "90849": "Multiple-family group psychotherapy",
    "90853": "Group psychotherapy",
    "90875": "Individual psychophysiological therapy, 30 min",
    "90876": "Individual psychophysiological therapy, 45 min",
    "96127": "Brief emotional/behavioral assessment",
    "96130": "Psychological testing evaluation, first hour",
    "96131": "Psychological testing evaluation, each additional hour",
    "96136": "Psychological testing administration, first 30 min",
    "96137": "Psychological testing administration, each additional 30 min",
    # ---------------------------------------------------------------------------
    # Substance Use Disorder (HCPCS H-codes)
    # ---------------------------------------------------------------------------
    "H0001": "Alcohol/drug assessment",
    "H0004": "Behavioral health counseling/therapy, per 15 min",
    "H0005": "Alcohol/drug services, group counseling",
    "H0006": "Alcohol/drug services, case management",
    "H0010": "Alcohol/drug services, sub-acute detox, residential",
    "H0015": "Alcohol/drug treatment, intensive outpatient",
    "H0020": "Alcohol/drug treatment program",
    "H0022": "Alcohol/drug intervention",
    "H2011": "Crisis intervention, per 15 min",
    "H2014": "Skills training and development, per 15 min",
    "H2015": "Comprehensive community support services, per 15 min",
    "H2017": "Psychosocial rehabilitation, per 15 min",
    "H2019": "Therapeutic behavioral services, per 15 min",
    "H2021": "Community-based wrap-around services, per 15 min",
    "H2035": "Alcohol/drug treatment per diem",
    # ---------------------------------------------------------------------------
    # Laboratory
    # ---------------------------------------------------------------------------
    "80047": "Basic metabolic panel (ionized calcium)",
    "80048": "Basic metabolic panel",
    "80050": "General health panel",
    "80053": "Comprehensive metabolic panel",
    "80061": "Lipid panel",
    "80076": "Hepatic function panel",
    "81001": "Urinalysis with microscopy",
    "81002": "Urinalysis without microscopy",
    "81003": "Urinalysis, automated, without microscopy",
    "82043": "Urine albumin, quantitative",
    "82306": "Vitamin D, 25-hydroxy",
    "82565": "Creatinine, blood",
    "82570": "Creatinine, urine",
    "82607": "Vitamin B12",
    "82728": "Ferritin",
    "82947": "Glucose, quantitative, blood",
    "82950": "Glucose, post-glucose dose",
    "82951": "Glucose tolerance test, 3 specimens",
    "83036": "Hemoglobin A1c",
    "83540": "Iron",
    "83550": "Iron binding capacity",
    "83718": "HDL cholesterol",
    "83721": "LDL cholesterol, direct measurement",
    "84132": "Potassium, serum",
    "84295": "Sodium, serum",
    "84443": "TSH (thyroid stimulating hormone)",
    "84450": "AST (aspartate aminotransferase)",
    "84460": "ALT (alanine aminotransferase)",
    "84478": "Triglycerides",
    "84484": "Troponin, quantitative",
    "84702": "hCG, quantitative (pregnancy test)",
    "84703": "hCG, qualitative (pregnancy test)",
    "85025": "CBC with differential",
    "85027": "CBC without differential",
    "85610": "Prothrombin time (PT)",
    "85730": "Partial thromboplastin time (PTT)",
    "86592": "Syphilis test, qualitative",
    "86593": "Syphilis test, quantitative",
    "86617": "Lyme disease antibody, confirmatory",
    "86631": "Chlamydia antibody",
    "86694": "Herpes simplex antibody, type 1",
    "86695": "Herpes simplex antibody, type 2",
    "86703": "HIV-1/HIV-2 antibody, combination",
    "86706": "Hepatitis B surface antibody",
    "86762": "Rubella antibody",
    "86803": "Hepatitis C antibody",
    "87040": "Blood culture",
    "87070": "Culture, bacterial, other source",
    "87081": "Urine culture, presumptive",
    "87086": "Urine culture, quantitative",
    "87110": "Chlamydia culture",
    "87340": "Hepatitis B surface antigen",
    "87389": "HIV-1 antigen/antibody combination",
    "87426": "Influenza A & B antigen detection",
    "87427": "Respiratory syncytial virus (RSV) antigen",
    "87449": "Infectious agent antigen, NOS",
    "87491": "Chlamydia, amplified probe technique",
    "87591": "Gonorrhea, amplified probe technique",
    "87621": "HPV, high risk types",
    "87624": "HPV, types 6, 11",
    "87625": "HPV, types 16, 18",
    "87631": "Respiratory virus panel, 12-25 targets",
    "87633": "Respiratory virus panel, >25 targets",
    "87635": "COVID-19 antigen detection",
    "87804": "Influenza A antigen",
    "87807": "RSV antigen, direct optical",
    "87880": "Streptococcus A antigen (rapid strep)",
    "87899": "Infectious agent antigen, not otherwise specified",
    "88305": "Tissue exam by pathologist, level IV",
    "88307": "Tissue exam by pathologist, level V",
    # ---------------------------------------------------------------------------
    # Vaccines & Immunization Administration
    # ---------------------------------------------------------------------------
    "90460": "Immunization administration, first vaccine, ≤18 years",
    "90461": "Immunization administration, each additional vaccine, ≤18 years",
    "90471": "Immunization administration, first vaccine",
    "90472": "Immunization administration, each additional vaccine",
    "90473": "Immunization administration, intranasal/oral, first vaccine",
    "90474": "Immunization administration, intranasal/oral, each additional",
    "90630": "Influenza virus vaccine, quadrivalent, intradermal",
    "90647": "Haemophilus influenzae b (Hib) vaccine",
    "90648": "Hib vaccine, PRP-T conjugate",
    "90651": "HPV9 vaccine",
    "90654": "Influenza vaccine, trivalent, preservative free",
    "90655": "Influenza vaccine, trivalent, for children",
    "90656": "Influenza vaccine, trivalent, preservative free",
    "90658": "Influenza vaccine, trivalent, 3 years and older",
    "90660": "Influenza vaccine, live, intranasal",
    "90670": "Pneumococcal conjugate vaccine, 13-valent (PCV13)",
    "90672": "Influenza vaccine, quadrivalent, live intranasal",
    "90673": "Influenza vaccine, trivalent, recombinant",
    "90674": "Influenza vaccine, quadrivalent, ccIIV4",
    "90680": "Rotavirus vaccine, live, oral",
    "90681": "Rotavirus vaccine, human, monovalent",
    "90686": "Influenza vaccine, quadrivalent, preservative free",
    "90688": "Influenza vaccine, quadrivalent",
    "90694": "Influenza vaccine, quadrivalent, adjuvanted (aIIV4)",
    "90696": "DTaP-IPV vaccine",
    "90698": "DTaP-IPV-Hib vaccine",
    "90700": "DTaP vaccine",
    "90702": "DT vaccine",
    "90707": "MMR vaccine",
    "90710": "MMRV vaccine",
    "90713": "Poliovirus vaccine, inactivated (IPV)",
    "90714": "Td vaccine, preservative free",
    "90715": "Tdap vaccine",
    "90716": "Varicella (chickenpox) vaccine",
    "90717": "Yellow fever vaccine",
    "90723": "DTaP-IPV-HepB-Hib vaccine",
    "90732": "Pneumococcal polysaccharide vaccine, 23-valent (PPSV23)",
    "90734": "Meningococcal vaccine, serogroups A, C, Y, W-135",
    "90736": "Zoster (shingles) vaccine, live",
    "90739": "Hepatitis B vaccine, 2-dose schedule, adult",
    "90740": "Hepatitis B vaccine, dialysis dosage",
    "90743": "Hepatitis B vaccine, 2-dose schedule, adolescent",
    "90744": "Hepatitis B vaccine, pediatric",
    "90746": "Hepatitis B vaccine, adult",
    "90747": "Hepatitis B vaccine, 4-dose schedule, dialysis",
    "90748": "HepB-Hib vaccine",
    "90750": "Zoster vaccine, recombinant (Shingrix), first dose",
    "90756": "Influenza vaccine, quadrivalent, intradermal",
    "91300": "COVID-19 vaccine, Pfizer-BioNTech, 30mcg/0.3mL",
    "91301": "COVID-19 vaccine, Moderna, 100mcg/0.5mL",
    "91302": "COVID-19 vaccine, AstraZeneca",
    "91303": "COVID-19 vaccine, Janssen (J&J)",
    "91304": "COVID-19 vaccine, Novavax",
    "91305": "COVID-19 vaccine, Pfizer, tris-sucrose, 30mcg/0.3mL",
    "91307": "COVID-19 vaccine, Pfizer-BioNTech, orange cap, 10mcg/0.2mL",
    "91308": "COVID-19 vaccine, Pfizer-BioNTech, maroon cap, 3mcg/0.2mL",
    # G-codes for vaccine admin
    "G0008": "Influenza vaccination administration",
    "G0009": "Pneumococcal vaccination administration",
    "G0010": "Hepatitis B vaccination administration",
    # ---------------------------------------------------------------------------
    # Common Procedures
    # ---------------------------------------------------------------------------
    "10060": "Incision and drainage of abscess, simple",
    "10061": "Incision and drainage of abscess, complicated",
    "10120": "Incision and removal of foreign body, simple",
    "10121": "Incision and removal of foreign body, complicated",
    "10160": "Puncture aspiration of abscess/hematoma",
    "11055": "Paring/cutting of benign hyperkeratotic lesion, first",
    "11056": "Paring/cutting of benign hyperkeratotic lesion, 2-4",
    "11057": "Paring/cutting of benign hyperkeratotic lesion, >4",
    "11720": "Debridement of nail(s), any method, 1-5",
    "11721": "Debridement of nail(s), any method, 6+",
    "11730": "Avulsion of nail plate, partial, simple",
    "12001": "Simple wound repair, scalp/neck/axillae/external genitalia/trunk/extremities, ≤2.5cm",
    "12002": "Simple wound repair, ≤2.5cm area",
    "12011": "Simple wound repair, face/ears/eyelids/nose/lips/mucous membranes, ≤2.5cm",
    "17000": "Destruction of premalignant lesion, first",
    "17003": "Destruction of premalignant lesion, each additional (2-14)",
    "17110": "Destruction of benign lesion, up to 14",
    "17111": "Destruction of benign lesion, 15 or more",
    "20550": "Injection, tendon sheath/ligament",
    "20551": "Injection, tendon origin/insertion",
    "20600": "Arthrocentesis, small joint",
    "20605": "Arthrocentesis, intermediate joint",
    "20610": "Arthrocentesis, major joint",
    "36415": "Venipuncture (routine blood draw)",
    "36416": "Capillary blood collection (fingerstick)",
    "45378": "Colonoscopy, diagnostic",
    "45380": "Colonoscopy with biopsy",
    "45385": "Colonoscopy with polypectomy, hot biopsy or snare",
    "45386": "Colonoscopy with dilation of stricture",
    "71045": "Chest X-ray, 1 view",
    "71046": "Chest X-ray, 2 views",
    "71047": "Chest X-ray, 3 views",
    "71048": "Chest X-ray, 4 or more views",
    "93000": "Electrocardiogram (ECG), with interpretation and report",
    "93005": "ECG, tracing only",
    "93010": "ECG, interpretation and report only",
    "96372": "Therapeutic, prophylactic, or diagnostic injection (IM or subcut)",
    "96374": "Therapeutic, prophylactic, or diagnostic injection, IV push",
    "96375": "Each additional sequential IV push",
    "96376": "Each additional sequential IV push, same substance/drug",
    "96360": "IV infusion, hydration, initial",
    "96361": "IV infusion, hydration, each additional hour",
    "96365": "IV infusion, therapeutic/diagnostic, initial, up to 1 hr",
    "96366": "IV infusion, therapeutic/diagnostic, each additional hour",
    "96401": "Chemotherapy, not hormonal, subcutaneous or IM",
    # ---------------------------------------------------------------------------
    # Radiology / Imaging
    # ---------------------------------------------------------------------------
    "70450": "CT head/brain without contrast",
    "70460": "CT head/brain with contrast",
    "70470": "CT head/brain without/with contrast",
    "70551": "MRI brain without contrast",
    "70552": "MRI brain with contrast",
    "70553": "MRI brain without/with contrast",
    "71250": "CT thorax without contrast",
    "71260": "CT thorax with contrast",
    "71270": "CT thorax without/with contrast",
    "72100": "X-ray lumbar spine, 2-3 views",
    "72110": "X-ray lumbar spine, min 4 views",
    "72148": "MRI lumbar spine without contrast",
    "72149": "MRI lumbar spine with contrast",
    "72158": "MRI lumbar spine without/with contrast",
    "73060": "X-ray humerus, min 2 views",
    "73070": "X-ray elbow, 2 views",
    "73080": "X-ray elbow, min 3 views",
    "73090": "X-ray forearm, 2 views",
    "73100": "X-ray wrist, 2 views",
    "73110": "X-ray wrist, min 3 views",
    "73120": "X-ray hand, 2 views",
    "73130": "X-ray hand, min 3 views",
    "73140": "X-ray finger(s), min 2 views",
    "73560": "X-ray knee, 1-2 views",
    "73562": "X-ray knee, 3 views",
    "73564": "X-ray knee, AP weight bearing",
    "73590": "X-ray tibia/fibula, 2 views",
    "73600": "X-ray ankle, 2 views",
    "73610": "X-ray ankle, min 3 views",
    "73620": "X-ray foot, 2 views",
    "73630": "X-ray foot, min 3 views",
    "73650": "X-ray calcaneus, min 2 views",
    "74177": "CT abdomen/pelvis with contrast",
    "74178": "CT abdomen/pelvis without/with contrast",
    "74181": "MRI abdomen without contrast",
    "76700": "Ultrasound abdomen, complete",
    "76705": "Ultrasound abdomen, limited",
    "76770": "Ultrasound retroperitoneal, complete",
    "76775": "Ultrasound retroperitoneal, limited",
    "76801": "Ultrasound pregnant uterus, 1st trimester",
    "76805": "Ultrasound pregnant uterus, 2nd/3rd trimester",
    "76856": "Ultrasound pelvis, complete",
    "76857": "Ultrasound pelvis, limited",
    "76870": "Ultrasound scrotum",
    "76881": "Ultrasound extremity, complete",
    "76882": "Ultrasound extremity, limited",
    "93303": "Echocardiography, transthoracic, congenital",
    "93306": "Echo with color-flow Doppler",
    "93308": "Follow-up or limited echo",
    "93351": "Stress echocardiography",
    # ---------------------------------------------------------------------------
    # Cardiac / Monitoring
    # ---------------------------------------------------------------------------
    "93224": "External ECG monitor, up to 48 hr recording",
    "93226": "External ECG monitor, recording",
    "93227": "External ECG monitor, scanning analysis",
    "93228": "External mobile cardiac telemetry, recording",
    "93229": "External mobile cardiac telemetry, analysis/report",
    "93270": "Patient-activated event recorder, transmission",
    "93271": "Patient-activated event recorder, analysis",
    # ---------------------------------------------------------------------------
    # Physical / Occupational Therapy
    # ---------------------------------------------------------------------------
    "97010": "Application of hot or cold packs",
    "97012": "Traction, mechanical",
    "97014": "Electrical stimulation (unattended)",
    "97016": "Vasopneumatic device therapy",
    "97018": "Paraffin bath",
    "97022": "Whirlpool",
    "97032": "Electrical stimulation (manual), 15 min",
    "97033": "Iontophoresis, 15 min",
    "97035": "Ultrasound, 15 min",
    "97036": "Hubbard tank, 15 min",
    "97110": "Therapeutic exercises, 15 min",
    "97112": "Neuromuscular reeducation, 15 min",
    "97116": "Gait training, 15 min",
    "97124": "Massage, 15 min",
    "97140": "Manual therapy techniques, 15 min",
    "97150": "Therapeutic exercises, group",
    "97161": "Physical therapy evaluation, low complexity",
    "97162": "Physical therapy evaluation, moderate complexity",
    "97163": "Physical therapy evaluation, high complexity",
    "97164": "Physical therapy re-evaluation",
    "97165": "Occupational therapy evaluation, low complexity",
    "97166": "Occupational therapy evaluation, moderate complexity",
    "97167": "Occupational therapy evaluation, high complexity",
    "97168": "Occupational therapy re-evaluation",
    "97530": "Therapeutic activities, 15 min",
    "97535": "Self-care/home management training, 15 min",
    "97542": "Wheelchair management, 15 min",
    "97750": "Physical performance test, 15 min",
    "97760": "Orthotic management and training, 15 min",
    "97761": "Prosthetic training, 15 min",
    # ---------------------------------------------------------------------------
    # Chiropractic
    # ---------------------------------------------------------------------------
    "98940": "Chiropractic manipulation, 1-2 spinal regions",
    "98941": "Chiropractic manipulation, 3-4 spinal regions",
    "98942": "Chiropractic manipulation, 5 spinal regions",
    "98943": "Chiropractic manipulation, extraspinal",
    # ---------------------------------------------------------------------------
    # Drug Injections (J-codes)
    # ---------------------------------------------------------------------------
    "J0120": "Tetracycline, 250mg injection",
    "J0129": "Abatacept, 10mg",
    "J0135": "Adalimumab, 20mg",
    "J0178": "Aflibercept, 1mg",
    "J0360": "Hydralazine HCl, 20mg",
    "J0456": "Azithromycin, 500mg",
    "J0585": "Botulinum toxin type A, 1 unit",
    "J0696": "Ceftriaxone sodium, 250mg",
    "J0702": "Betamethasone acetate/phosphate, 3mg",
    "J0780": "Prochlorperazine, 10mg",
    "J1030": "Methylprednisolone acetate, 40mg",
    "J1040": "Methylprednisolone acetate, 80mg",
    "J1050": "Medroxyprogesterone acetate, 150mg",
    "J1055": "Medroxyprogesterone acetate for contraception, 150mg",
    "J1100": "Dexamethasone sodium phosphate, 1mg",
    "J1170": "Hydromorphone, up to 4mg",
    "J1200": "Diphenhydramine HCl, 50mg",
    "J1380": "Estradiol valerate, 10mg",
    "J1440": "Filgrastim, 300mcg",
    "J1441": "Filgrastim, 480mcg",
    "J1561": "Intravenous immune globulin, 500mg",
    "J1568": "Ivig, 500mg",
    "J1569": "Ivig, 500mg (Gammagard liquid)",
    "J1580": "Garamycin, 80mg",
    "J1599": "Ivig, not otherwise classified",
    "J1631": "Haloperidol, up to 5mg",
    "J1642": "Heparin sodium, 10 units",
    "J1644": "Heparin sodium, 1000 units",
    "J1650": "Enoxaparin sodium, 10mg",
    "J1885": "Ketorolac tromethamine, 15mg",
    "J2001": "Lidocaine HCl for IV infusion, 10mg",
    "J2060": "Lorazepam, 2mg",
    "J2175": "Meperidine HCl, 100mg",
    "J2250": "Midazolam HCl, 1mg",
    "J2270": "Morphine sulfate, up to 10mg",
    "J2310": "Naloxone HCl, 1mg",
    "J2315": "Naltrexone, 380mg extended release",
    "J2405": "Ondansetron HCl, 1mg",
    "J2550": "Promethazine HCl, up to 50mg",
    "J2680": "Fluphenazine decanoate, up to 25mg",
    "J2790": "Rho(D) immune globulin, 300mcg",
    "J3010": "Fentanyl citrate, 0.1mg",
    "J3030": "Sumatriptan succinate, 6mg",
    "J3105": "Terbutaline sulfate, up to 1mg",
    "J3240": "Thyrotropin alpha, 0.9mg",
    "J3301": "Triamcinolone acetonide, 10mg",
    "J3302": "Triamcinolone diacetate, 5mg",
    "J3303": "Triamcinolone hexacetonide, 5mg",
    "J3360": "Diazepam, 5mg",
    "J3370": "Vancomycin HCl, 500mg",
    "J3420": "Vitamin B12 (cyanocobalamin), 1000mcg",
    "J3430": "Vitamin K phytonadione, 1mg",
    "J3490": "Unclassified drugs",
    "J3590": "Unclassified biologics",
    "J7030": "Saline solution, 1000mL",
    "J7040": "Normal saline, 500mL",
    "J7042": "5% dextrose/normal saline, 500mL",
    "J7050": "Normal saline, 250mL",
    "J7060": "5% dextrose/water, 1000mL",
    "J7070": "D5W, 5% dextrose/water, 250mL",
    "J7120": "Ringers lactate, 1000mL",
    "J7170": "Enoxaparin sodium, 1mg",
    "J7300": "Intrauterine copper contraceptive",
    "J7301": "Levonorgestrel-releasing IUD, 52mg",
    "J7302": "Levonorgestrel-releasing IUD, 13.5mg",
    "J7307": "Etonogestrel implant system",
    "J7620": "Albuterol, inhalation solution, 1mg",
    "J7626": "Budesonide inhalation solution, 0.25mg",
    "J7644": "Ipratropium bromide inhalation solution, 0.2mg",
    # ---------------------------------------------------------------------------
    # DME / Supplies (E & A codes)
    # ---------------------------------------------------------------------------
    "A4206": "Syringe with needle, sterile",
    "A4550": "Surgical trays",
    "A4570": "Splint",
    "A9270": "Non-covered item or service",
    "E0100": "Cane, includes cane tips",
    "E0105": "Cane, quad/3-prong",
    "E0110": "Crutches, forearm",
    "E0114": "Crutches, underarm, pair",
    "E0117": "Crutch, underarm, articulating",
    "E0130": "Walker, rigid (pickup)",
    "E0135": "Walker, folding (pickup)",
    "E0141": "Walker, rigid, wheeled",
    "E0143": "Walker, folding, wheeled",
    "E0190": "Positioning cushion/pillow/wedge",
    "E0197": "Air pressure mattress",
    "E0260": "Hospital bed, semi-electric",
    "E0265": "Hospital bed, total electric",
    "E0601": "Continuous positive airway pressure (CPAP) device",
    "E0604": "Breast pump, hospital grade, electric",
    "E0627": "Seat lift mechanism, electric",
    "E1390": "Oxygen concentrator, single delivery",
    "E1392": "Portable oxygen concentrator, rental",
    "K0001": "Standard manual wheelchair",
    "K0003": "Lightweight wheelchair",
    "K0004": "High strength, lightweight wheelchair",
    "K0005": "Ultralightweight wheelchair",
    "K0007": "Heavy duty wheelchair",
    "K0108": "Wheelchair component or accessory, NOS",
    # ---------------------------------------------------------------------------
    # Home Health (G-codes)
    # ---------------------------------------------------------------------------
    "G0151": "Services of physical therapist, home health",
    "G0152": "Services of occupational therapist, home health",
    "G0153": "Services of speech-language pathologist, home health",
    "G0154": "Services of skilled nurse, home health",
    "G0155": "Services of medical social worker, home health",
    "G0156": "Services of home health aide",
    "G0299": "Direct skilled nursing services, home health",
    "G0300": "Direct skilled nursing services, home health, per 15 min",
    # ---------------------------------------------------------------------------
    # Preventive / Screening (G-codes)
    # ---------------------------------------------------------------------------
    "G0101": "Cervical/vaginal cancer screening (pelvic exam)",
    "G0102": "Prostate cancer screening, digital rectal exam",
    "G0103": "Prostate cancer screening, PSA test",
    "G0104": "Colorectal cancer screening, flexible sigmoidoscopy",
    "G0105": "Colorectal cancer screening, high-risk colonoscopy",
    "G0107": "Colorectal cancer screening, fecal occult blood test",
    "G0108": "Diabetes self-management training, individual, 30 min",
    "G0109": "Diabetes self-management training, group, 30 min",
    "G0117": "Glaucoma screening, high-risk patient, by optometrist",
    "G0118": "Glaucoma screening, high-risk patient, by MD",
    "G0121": "Colorectal cancer screening, colonoscopy, avg risk",
    "G0202": "Screening mammography",
    "G0204": "Diagnostic mammography, bilateral",
    "G0206": "Diagnostic mammography, unilateral",
    "G0396": "Alcohol/substance abuse structured assessment, 15-30 min",
    "G0397": "Alcohol/substance abuse structured assessment, >30 min",
    "G0438": "Annual wellness visit, initial",
    "G0439": "Annual wellness visit, subsequent",
    "G0442": "Annual alcohol misuse screening",
    "G0443": "Brief counseling for alcohol misuse, 15 min",
    "G0444": "Annual depression screening",
    "G0445": "HIV prevention behavioral counseling, high-intensity",
    "G0446": "Intensive behavioral therapy for cardiovascular disease",
    "G0447": "Face-to-face behavioral counseling for obesity, 15 min",
    "G0473": "Behavioral counseling for obesity, group visit",
    "G0506": "Care planning for chronic care management",
    # Telehealth
    "G2012": "Brief communication technology-based service, 5-10 min",
    "G2025": "Telehealth originating site facility fee",
    "G2061": "Qualified nonphysician provider, telehealth, 5-10 min",
    "G2062": "Qualified nonphysician provider, telehealth, 11-20 min",
    "G2063": "Qualified nonphysician provider, telehealth, 21-30 min",
    # ---------------------------------------------------------------------------
    # Ambulance (A-codes)
    # ---------------------------------------------------------------------------
    "A0425": "Ground mileage, per statute mile",
    "A0426": "Ambulance service, ALS, non-emergency",
    "A0427": "Ambulance service, ALS, emergency",
    "A0428": "Ambulance service, BLS, non-emergency",
    "A0429": "Ambulance service, BLS, emergency",
    "A0430": "Ambulance service, air transport, fixed wing",
    "A0431": "Ambulance service, air transport, rotary wing",
    "A0433": "Advanced life support, level 2",
    "A0434": "Specialty care transport",
    "A0435": "Fixed wing air mileage, per statute mile",
    "A0436": "Rotary wing air mileage, per statute mile",
}


def get_description(code: str) -> str:
    """Return the description for a HCPCS/CPT code, or empty string if unknown."""
    return HCPCS_DESCRIPTIONS.get(str(code).strip().upper(), "")
